config/routes.rb
SampleRailsApp::Application.routes.draw do

  devise_for :users

 resources :movies
 resources :actors
 resources :home

   root :to => 'home#index'

end

app/models/actor.rb
class Actor < ActiveRecord::Base
  attr_accessible :name
  has_many :movies, :dependent => :nullify

  self.per_page = 10

  validates_presence_of :name
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  attr_accessible :language, :name, :release_date, :actor_id, :id
  belongs_to :actor
  belongs_to :user

  validates_uniqueness_of :name

  def self.languages
  	["English","Hindi"]
  end

  self.per_page = 10
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
          :token_authenticatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :movies
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController

	before_filter :require_user
	before_filter :get_actor, :only=>[:edit, :update, :destroy]
	
	def index
		@actors = Actor.page(params[:page]).order('name ASC')
	end

	def new
		@actor = Actor.new
	end

	def create
		@actor = Actor.new(params[:actor])
		begin
			Actor.transaction do
				@actor.save!
			end
			flash[:success] = "Actor created successfully"
			redirect_to actors_path
		rescue => e
			flash.now[:error] = "Something went wrong: #{e}" 
      render :action => "new"
		end
	end

	def edit
	end

	def update
		@actor.update_attributes(params[:actor])
		begin
			Actor.transaction do 
			@actor.save!
			end
			flash[:success] = "Actor updated successfully"
			redirect_to actors_path	
		rescue => e
			flash.now[:error] = "Something went wrong: #{e}" 
			render :action => 'edit'
		end
		
	end

	def destroy
		@actor.destroy
		redirect_to actors_path
	end

	def get_actor
		@actor = Actor.find_by_id(params[:id])
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def require_user
  	if !current_user
  		redirect_to home_index_path
  		return
  	end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

def index
@movies = Movie.page(params[:page]).find(:all, :limit => 5, :order=> 'created_at desc')
end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
	
	before_filter :require_user
	before_filter :get_movie, :only => [:edit, :update, :destroy]

	def index
		if params[:movie]
	      @movie = Movie.new(params[:movie])
     
	      and_conditions = []
	      condition_values = {}
	      unless @movie.id.nil?
	        and_conditions.push "movies.id like :id"
	        condition_values[:id] = "#{@movie.id}"
	      end
	      unless @movie.name.nil?
	        and_conditions.push "movies.name like :name"
	        condition_values[:name] = "%" + "#{@movie.name}" + "%"
	      end
	      unless @movie.actor_id.nil?
	      	and_conditions.push "movies.actor_id like :actor_id"
	      	condition_values[:actor_id] = "#{@movie.actor_id}"
	      end
	      unless @movie.language.nil?
	      	and_conditions.push "movies.language like :language"
	      	condition_values[:language] = "%" + "#{@movie.language}" + "%"
	      end
	      unless @movie.release_date.nil?
	      	and_conditions.push "movies.release_date like :release_date"
	      	condition_values[:release_date] = "#{@movie.release_date}"
	      end
	      
	      if and_conditions.size > 0
	        conditions = [and_conditions.join(" AND "), condition_values]
	      end
	      
	    end
	    

	    @params = params
	    
	    order = []
	    joins = ""
	    if params[:sort]
	    
	      if params[:sort] == params[:last_sort]
	        direction = "DESC"
	        @last_sort = ""
	      else
	        direction = "ASC"
	        @last_sort = params[:sort]
	      end
	      
	      case params[:sort]
	      	when "id"
	          order.push "movies.id #{direction}"
					when "name"
	          order.push "movies.name #{direction}"
	        when "language"
	          order.push "movies.language #{direction}"
	        when "release_date"
	        	order.push "movies.release_date #{direction}"
	        when "created_at"
	          order.push "movies.created_at #{direction}"
	        when "actor_id"
	        	order.push "movies.actor_id #{direction}"
	      end
	    end
	    
	    order.push "movies.id DESC"
	    
	    order_string = order.join(", ") 

		#@movies = Movie.page(params[:page]).order('created_at DESC')
		@movies = Movie.paginate(:order => order_string, :page => params[:page], :conditions => conditions)
	end

	def new
		@movie = current_user.movies.build
	end

	def create
		@movie = current_user.movies.build(params[:movie])
		begin
			Movie.transaction do
				@movie.save!
			end
			flash[:success] = "Movie created successfully"
			redirect_to movies_path
		rescue => e
      	flash.now[:error] = "Something went wrong: #{e}" 
      	render :action => "new"
    end
	end

	def edit
	end

	def update
		@movie.update_attributes(params[:movie])
		begin
			Movie.transaction do 
				@movie.save!
			end
			flash[:success] = "Movie updated successfully"
			redirect_to movies_path
		rescue => e
			flash.now[:error] = "Something went wrong: #{e}" 
			render :action => "edit"
		end
	end

	def destroy
		@movie.destroy
		redirect_to movies_path
	end

	def get_movie
		@movie = Movie.find_by_id(params[:id])
	end

end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def bootstrap_class_for flash_type
    # case flash_type
    #   when :success
    #     "alert-success"
    #   when :error
    #     "alert-error"
    #   when :alert
    #     "alert-block"
    #   when :notice
    #     "alert-info"
    #   else
    #     flash_type.to_s
    # end
    {success: 'alert-success', error: 'alert-error', alert: 'alert-block', notice: 'alert-info'}[flash_type] || flash_type.to_s
  end

  def sort_link(order_by)
    @params ||= {}
    url_for(@params.merge({:sort => order_by, :page => @page, :last_sort => @last_sort.nil? ? nil : @last_sort}))
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/actors/_form.html.erb
<%= form_for @actor, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                actors_path, :class => 'btn' %>
  </div>
<% end %>

app/views/actors/edit.html.erb
<%- model_class = Actor -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/actors/index.html.erb
<%- model_class = Actor -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @actors.each do |actor| %>
      <tr>
        <td><%= link_to actor.id, actor_path(actor) %></td>
        <td><%= actor.name %></td>
        <td><%=l actor.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_actor_path(actor), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      actor_path(actor),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @actors %>
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_actor_path,
            :class => 'btn btn-primary' %>

app/views/actors/new.html.erb
<%- model_class = Actor -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/actors/show.html.erb
<%- model_class = Actor -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @actor.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              actors_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_actor_path(@actor), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              actor_path(@actor),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/home/index.html.erb
<div style="margin-top: 3em;">
<%if current_user%>
<ul>
<li><%= link_to "Manage Actors", actors_path%></li>
<li><%= link_to "Manage Movies", movies_path%></li>
</ul>
<%end%>
</div>
<%- model_class =  Movie -%>
<div class="page-header">
  <h1><%=t '.title', :default => 'Latest Movies' %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:language) %></th>
      <th><%= model_class.human_attribute_name(:release_date) %></th>
      <th><%= model_class.human_attribute_name(:actor_id) %></th>
    </tr>
  </thead>
  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= movie.name %></td>
        <td><%= movie.language %></td>
        <td><%= movie.release_date %></td>
        <td><%= movie.actor.andand.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SampleRailsApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class='container'>
<%= render partial: "shared/flash_messages", flash: flash %> 
<%= render :partial => 'shared/top_menu' %>
	<%= yield %>
</div>

</body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :language, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :language, Movie.languages, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :release_date, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :release_date, :class => 'text_field', :id=>'release_date' %>
      <%= image_tag("cal-icon.png", :class => "calendar-icon", :id => 'release_date_trigger') %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :actor_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.select :actor_id, Actor.find(:all, :order => "name ASC").collect {|a| [a.name, a.id]},{:include_blank=>"Please Select"}, :class => 'number_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                movies_path, :class => 'btn' %>
  </div>
<% end %>
<script type="text/javascript">
     Calendar.setup(
       {
         inputField  : "release_date",         // ID of the input field
         ifFormat    : "%Y-%m-%d",    // the date format
         button: 'release_date_trigger'
       }
     );
</script>

app/views/movies/edit.html.erb
<%- model_class = Movie -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/movies/index.html.erb
<div class= 'styled-form'>
<div class="page-header">
  <h4><%=t '.title', :default => 'Search' %></h4>
</div>
<%= form_for :movie , :url => movies_url, :html => {:method => :get} do |f| %>
  <%= f.label :id, "ID", :class => "info-box-label" %><%= f.text_field :id %><div class="clear"></div>
  <%= f.label :name %><%= f.text_field :name %><div class="clear"></div>
  <%= f.label :language %><%= f.select :language, Movie.languages,{:include_blank => "Select"}, :class => 'text_field' %><div class="clear"></div>
  <%= f.label :actor %><%= f.select :actor_id, Actor.find(:all, :order => "name ASC").collect {|a| [a.name, a.id]},{:include_blank=>"Please Select"}, :class => 'number_field' %><div class="clear"></div>
  <%= f.label :release_date %><%= f.text_field :release_date, :class => 'short-box-input-one', :id=>'release_date'%>
  <%= image_tag("cal-icon.png", :class => "calendar-icon", :id => 'release_date_trigger') %>
  <div class="clear"></div>
  

  <%= submit_tag("Filter") %>
<% end %>

</div>

<div class="clear"></div>
<%- model_class = Movie -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= link_to "#{model_class.human_attribute_name(:id)}", sort_link("id") %></th>
      <th><%= link_to "#{model_class.human_attribute_name(:name)}",  sort_link("name") %></th>
      <th><%= link_to "#{model_class.human_attribute_name(:language)}",  sort_link("language")  %></th>
      <th><%= link_to "#{model_class.human_attribute_name(:release_date)}",  sort_link("release_date")  %></th>
      <th><%= link_to "#{model_class.human_attribute_name(:actor_id)}",  sort_link("actor_id")  %></th>
      <th><%= link_to "#{model_class.human_attribute_name(:created_at)}",  sort_link("created_at")  %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td><%= link_to movie.id, movie_path(movie) %></td>
        <td><%= movie.name %></td>
        <td><%= movie.language %></td>
        <td><%= movie.release_date %></td>
        <td><%= movie.actor.andand.name %></td>
        <td><%=l movie.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_movie_path(movie), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      movie_path(movie),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @movies %>
<%#= will_paginate(@movies, :renderer => WillPaginate::ActionView::LinkRenderer) %>
<%= link_to t('Add new'),
            new_movie_path,
            :class => 'btn btn-primary' %>
<script type="text/javascript">
     Calendar.setup(
       {
         inputField  : "release_date",         // ID of the input field
         ifFormat    : "%Y-%m-%d",    // the date format
         button: 'release_date_trigger'
       }
     );
</script>

app/views/movies/new.html.erb
<%- model_class = Movie -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/movies/show.html.erb
<%- model_class = Movie -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @movie.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:language) %>:</strong></dt>
  <dd><%= @movie.language %></dd>
  <dt><strong><%= model_class.human_attribute_name(:release_date) %>:</strong></dt>
  <dd><%= @movie.release_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:actor_id) %>:</strong></dt>
  <dd><%= @movie.actor_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              movies_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_movie_path(@movie), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              movie_path(@movie),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/shared/_search_box.html.erb
<form class="form-search">
<div class="input-append">
<%= select_tag "action", options_for_select([["Actor" , "actor"],["Movie" , "movie"],["Date" , "date"]]), :class=>'search-select'%>
<input type="text" class="span2 search-query" id='search_release_date'>
<%= image_tag("cal-icon.png", :class => "calendar-icon", :id => 'search_release_date_trigger', :style=>'display:none;') %>
<button type="submit" class="btn">Search</button>
</div>
</form>

<script type="text/javascript">
$(function() {
$( "#action" ).change(function() {
  if ($('#action option:selected').text()=="Date")
     $('#search_release_date_trigger').show();
  else
     $('#search_release_date_trigger').hide();
 });
});
Calendar.setup(
       {
         inputField  : "search_release_date",         // ID of the input field
         ifFormat    : "%Y-%m-%d",    // the date format
         button: 'search_release_date_trigger'
       }
     );

</script>

app/views/shared/_top_menu.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <ul class="nav">
        <a class="brand" href="/"><%= image_tag "navigationlogo.png", :size=>"24x21", :alt=>"Home"%></a>
      </ul>
    
    <span class='search_box'>
      <%#= render :partial => 'shared/search_box'%>
    </span>

    <span style='float: right; padding-top: 10px; color: burlyWood;'>

      <% if user_signed_in? %>
        Signed in as <%= current_user.email %>. Not you?
        <%= link_to "Sign out", destroy_user_session_path, :method => :delete %>
      <% else %>
        <%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %>
      <% end %>
  	</span>

    </div>


  </div>

</div>